version: "3"

volumes:
  data:

networks:
  traefik-network:
    external: true

  traefik-hub: {}
  mq-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - traefik-hub

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
      - target: 6379
    networks:
      - traefik-hub

  ipfs:
    networks:
      - traefik-hub
    image: ipfs/go-ipfs:latest
    command:
      - daemon
      - --migrate=true
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse

    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata

    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001

    expose:
      - 8080:8080
      - 4001:4001
      - 5001:5001

    volumes:
      - ./data/ipfs:/ipfsdata
      - /etc/fuse.conf:/etc/fuse.conf:ro
      - ./data/ipfs:/data/ipfs
      - ./data/export:/export

  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.1.0
    pull_policy: always
    container_name: hub-agent
    restart: "on-failure"
    command:
      - run
      - --hub.token=941fad5b-2dc7-4e5d-bcaf-8795237c49c9
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-hub
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    networks:
      - traefik-hub

  nuclei_backend:
    build:
      context: .
      dockerfile: Dockerfile.app

    expose:
      - 8000
    ports:
      - 8000:8000
      - "8443:8000"

    environment:
      - "DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432/postgres"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
      - ipfs
    links:
      - postgres
    restart: unless-stopped
    volumes:
      - data:/app/data
    networks:
      - traefik-hub
