version: "3"

volumes:
  data:

networks:
  traefik-network:
    external: true

  traefik-hub: {}
  mq-network:
    driver: bridge

  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - traefik-hub
      - my-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
      - target: 6379
    networks:
      - traefik-hub
      - my-network
    restart: always

  ipfs:
    networks:
      - traefik-hub
      - my-network
    image: ipfs/kubo:latest
    command:
      - daemon
      - --migrate=true
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true
    restart: always

    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse

    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata

    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
      - 5003:5003

    expose:
      - 8080:8080
      - 4001:4001
      - 5001:5001
      - 5003:5003

    volumes:
      - ./data/ipfs:/ipfsdata
      - /etc/fuse.conf:/etc/fuse.conf:ro
      - ./data/ipfs:/data/ipfs
      - ./data/export:/export

  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.1.0
    pull_policy: always
    container_name: hub-agent
    restart: "on-failure"
    command:
      - run
      - --hub.token=611c4868-c653-4397-bbc0-1d327ed3282a
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-hub
    depends_on:
      - traefik

  # Start Traefik with the latest version
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    networks:
      - traefik-hub

  nuclei_backend:
    build:
      context: .
      dockerfile: Dockerfile.app

    expose:
      - 8000
    ports:
      - 8000:8000
      - "8443:8000"

    environment:
      - "DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
      - ipfs
    links:
      - postgres
      - ipfs
      - redis
    restart: always
    volumes:
      - data:/app/data
    networks:
      - traefik-hub
      - my-network
